serviceConfig:
  scheme: http://
  hostName: 0.0.0.0
  port: 5432
  path: /api/movies/


loggerConfig:
  outputDir: ./logs/
  outputFile: test.log

databaseConfig:
  dbUsername: cs122bg36
  dbPassword: u7Neri2zMgPx.
  dbHostname: colin-baker-v3.ics.uci.edu
  dbPort: 3306

  dbDriver: com.mysql.cj.jdbc.Driver
  dbName: cs122bg36
  dbSettings: ?autoReconnect=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=PST

idmConfig:
  scheme: http://
  hostName: 0.0.0.0
  port: 1234
  path: /api/idm/

idmEndpoints:
  privilege: /privilege
